### ISSUE TITLE
Rebuild command list on Makefile update

### ISSUE THREAD

**Issue by zenopopovici** [Akecel/makefiles-runner#7]
Right now the command list only rebuilds on VSCode reload.

**Comment by jeremy-allocate** [comment]
I agree, would like to see this.  Although it's only painful when making Makefile updates which we don't do often I guess.

**Comment by jeremy-allocate** [comment]
Alternatively, a little refresh button in the header of your panel (like the workspace explorer has) would be cool so the user can just do it on demand.  Would avoid the complexity of watching the Makefile for changes.

**Comment by jeremy-allocate** [comment]
I took a quick stab at a way of re-reading the makefile (status bar item, right aligned).  PR is posted and available at https://github.com/Akecel/makefiles-runner/pull/15 @Akecel

**Comment by Akecel** [comment]
Thank you very much for this contribution. 
The PR has been merged and a new version [(v1.1.0)](https://github.com/Akecel/makefiles-runner/releases/tag/v1.1.0) of the extension has been published.

**Comment by Akecel** [comment]
@jeremy-allocate 

I had to revert the modification because it had created a bug that prevented the extension from being used (when clicking on a command in the panel, no reaction, no terminal opened and no make command executed). I thought your improvement was really interesting, if you can find a way of fixing this bug while keeping your improvement, I'd be happy to make a new version for that.

**Comment by jeremy-allocate** [comment]
Thanks for the heads up @Akecel, that shouldn't be too hard to find.  I'll fix it out on my fork an open another PR.
